### ISSUE TITLE
No implicit conversion from nil to integer

### ISSUE THREAD

**Issue by syncrou** [syncrou/shelby_pco#10]
```
Enter start of filename: ShelbyExport_20170207.csv
Importing ShelbyExport_20170207.csv from Shelby to PCO csv file...
Building PCO Headers...
Building PCO Output from Shelby Input csv...
Done!
./shelby_pco.rb:139:in `[]': no implicit conversion from nil to integer (TypeError)
	from ./shelby_pco.rb:139:in `block (2 levels) in csv_io'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1739:in `each'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1122:in `block in foreach'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1121:in `foreach'
	from ./shelby_pco.rb:137:in `block in csv_io'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from ./shelby_pco.rb:134:in `csv_io'
	from ./shelby_pco.rb:115:in `file_stupid_checks'
	from ./shelby_pco.rb:149:in `<main>'
[dbomhof@syncrou ~/syncrou/shelby_pco (master)]$
```

**Comment by syncrou** [comment]
Closing - This was due to a bad line in my file at row 0 (numbered columns)
