### ISSUE TITLE
Importing a live csv file not finishing after building the headers

### ISSUE THREAD

**Issue by syncrou** [syncrou/shelby_pco#4]
```
[dbomhof@syncrou ~/syncrou/shelby_pco (master)]$ ./shelby_pco.rb
Enter filename: ShelbyExport_20170207.csv
Importing ShelbyExport_20170207.csv from Shelby to PCO csv file...
Building PCO Headers...
/Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1256:in `initialize': No such file or directory @ rb_sysopen - ShelbyExport.csv (Errno::ENOENT)
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1256:in `open'
	from /Users/dbomhof/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1256:in `open'
	from ./shelby_pco.rb:128:in `csv_io'
	from ./shelby_pco.rb:123:in `file_stupid_checks'
	from ./shelby_pco.rb:157:in `<main>'
```

**Comment by syncrou** [comment]
I think this line needs access to the `filename` variable: https://github.com/syncrou/shelby_pco/blob/master/shelby_pco.rb#L128
